// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig } from "prisma/config";

// Charger explicitement le fichier .env à la racine
config({ path: resolve(process.cwd(), ".env") });

// Utiliser la variable d'environnement de Vercel, ou DATABASE_URL en fallback
const databaseUrl = process.env.BAHION_POSTGRES_URL || 
                    process.env.BAHIONDB_PRISMA_DATABASE_URL || 
                    process.env.DATABASE_URL || 
                    "postgresql://placeholder:placeholder@localhost:5432/placeholder";

// Debug: vérifier si une URL de base de données est chargée
if (databaseUrl.includes("placeholder")) {
  console.warn("⚠️  Database URL not found. Checking: BAHION_POSTGRES_URL, BAHIONDB_PRISMA_DATABASE_URL, DATABASE_URL");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
