// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig } from "prisma/config";

// Charger explicitement le fichier .env à la racine
config({ path: resolve(process.cwd(), ".env") });

// Utiliser DATABASE_URL en priorité, ou BAHIONDB_POSTGRES_URL en fallback
// IMPORTANT: Ne PAS utiliser les URLs Prisma Accelerate (prisma:// ou prisma+postgres://)
const databaseUrl = process.env.DATABASE_URL || 
                    process.env.BAHIONDB_POSTGRES_URL || 
                    "postgresql://placeholder:placeholder@localhost:5432/placeholder";

// Debug: vérifier si DATABASE_URL est chargée
if (databaseUrl.includes("placeholder")) {
  console.warn("⚠️  DATABASE_URL not found. Please set DATABASE_URL environment variable");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
