import type { Metadata } from "next";
import { Aladin } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const aladin = Aladin({
  weight: "400",
  variable: "--font-aladin",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${aladin.variable}  antialiased`}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
