-- AlterTable
ALTER TABLE "Ability" ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "Passive" ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "maxLevel" SET DEFAULT 20;

-- AlterTable
ALTER TABLE "Stigma" ADD COLUMN     "maxLevel" INTEGER NOT NULL DEFAULT 20,
ALTER COLUMN "level" SET DEFAULT 1;
